gateways:
  dwh:
    state_connection:
      type: postgres
      host: sql_mesh_state
      user: postgres
      password: postgres
      port: 5432
      database: sql_mesh_state
    connection:
      type: postgres
      host: sql_mesh_dwh
      user: postgres
      password: postgres
      port: 5432
      database: sql_mesh_dwh
  sample_data:
    state_connection:
      type: postgres
      host: sql_mesh_state
      user: postgres
      password: postgres
      port: 5432
      database: sql_mesh_state
    connection:
      type: motherduck
      database: sample_data
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvYnltZXNAZ21haWwuY29tIiwic2Vzc2lvbiI6InJvYnltZXMuZ21haWwuY29tIiwicGF0IjoiLXlnd3RNTmc4T0dnMmVnb24xVXdzWUZVQjUzRWZHSVJpT21EMTRmTFE2VSIsInVzZXJJZCI6IjAyMDJjMzA2LTljNWMtNGMzYS1iZGVlLTdlNWFlZTZkY2M0ZSIsImlzcyI6Im1kX3BhdCIsImlhdCI6MTcyNDQwNzkxOH0.vNEM1o48K0R78zC7xeCrQuGcJpCoyB6UG-hJL7fb7VI
default_gateway: dwh

model_defaults:
  dialect: duckdb
  start: 2000-01-01
